name: Build Exact Book

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install chess

      - name: Build main.bin from PGN
        run: |
          mkdir -p engines
          python create_polyglot.py forced-line.pgn engines/main.bin

      - name: Check main.bin size
        run: |
          stat engines/main.bin
          SIZE=$(stat --format="%s" engines/main.bin)
          if [ $((SIZE % 16)) -ne 0 ]; then
            echo "ERROR: main.bin size not multiple of 16"
            exit 1
          fi
          echo "✅ main.bin is valid"

      - name: Upload main.bin as artifact
        uses: actions/upload-artifact@v4
        with:
          name: bookforwin
          path: engines/main.bin
